[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd admin && npm install"]

[phases.build]
cmds = ["cd admin && npm run build"]

[start]
cmd = "cd admin && npm run preview -- --host 0.0.0.0 --port $PORT"

